name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@v1
    with:
      attestations: true
    permissions:
      contents: write
      id-token: write
      attestations: write
